apiVersion: apps/v1
kind: Deployment
metadata:
  name: ebony-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: ebony-app
  template:
    metadata:
      labels:
        app: ebony-app
    spec:
      containers:
      - name: ebony-app
        image: maweiyi/ebony-app:latest
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "0.5"
            memory: "500Mi"
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: external-mysql
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: password
        - name: DB_NAME
          value: test
        - name: REDIS_HOST
          value: external-redis
        - name: REDIS_PORT
          value: "6379"
